workflows:
  android-build:
    name: Build APK for JsPlsyer
    max_build_duration: 60
    environment:
      java: 17
      android:
        version: 34
    scripts:
      - name: Clean project
        script: |
          ./gradlew clean

      - name: Build APK
        script: |
          ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk

    publishing:
      email:
        recipients:
          - your-email@example.com
